### ISSUE TITLE
Script doesn't like spaces. Returns "File not matched"

### ISSUE THREAD

**Issue by AccountOneOff** [DrDoctor13/wine-origin-updater#1]
Enter Origin installation directory
    /home/cxf/Games/mass-effect-andromeda/drive_c/Program Files (x86)/Origin
    Archive:  ./update/OriginUpdate_10_5_15_44004.zip
    caution: filename not matched:  Files
    caution: filename not matched:  (x86)/Origin

Even with backslashes it still throws out that same dialog.

**Comment by DrDoctor13** [comment]
Try using this for your path and see if it works:

`/home/cxf/Games/mass-effect-andromeda/drive_c/Program\ Files\ (x86)/Origin`

Because of how bash handles spaces in commands, a \ character needs to be put before each space.

**Comment by AccountOneOff** [comment]
> Even with backslashes it still throws out that same dialog.

I did that.

**Comment by DrDoctor13** [comment]
You've put in too many backslashes. Run the path I gave you in my above comment exactly as it appears.

**Comment by AccountOneOff** [comment]
Same result.

**Comment by DrDoctor13** [comment]
I've investigated this myself and this behavior didn't happen when writing the initial script. I've changed `read` so it now uses readline to obtain the line (enabling tab completion) and putting the $path for `unzip` in quotes seemed to stop the "filename not matched" error. 

`Archive:  OriginSetup.exe
warning [OriginSetup.exe]:  640000 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  inflating: update/OriginUpdate_10_5_15_44004.zip  
Enter Origin installation directory
/home/bucks/Linux\ Games/Lutris/origin/drive_c/Program\ Files/Origin
Archive:  ./update/OriginUpdate_10_5_15_44004.zip
  inflating: /home/bucks/Linux Games/Lutris/origin/drive_c/Program Files/Origin/audio/qtaudio_windows.dll  
  inflating: /home/bucks/Linux Games/Lutris/origin/drive_c/Program Files/Origin/imageformats/qgif.dll  
  inflating: /home/bucks/Linux Games/Lutris/origin/drive_c/Program Files/Origin/imageformats/qico.dll  
  inflating: /home/bucks/Linux Games/Lutris/origin/drive_c/Program Files/Origin/imageformats/qjpeg.dll  
  inflating: /home/bucks/Linux Games/Lutris/origin/drive_c/Program Files/Origin/imageformats/qsvg.dll
` 
Can you test this new commit and see if it fixes the problem on your end?

**Comment by AccountOneOff** [comment]
Yup that worked! Great script!

**Comment by DrDoctor13** [comment]
Glad I could help. This is my first script so I'm learning as I go along. Thank you for reporting the error!
