### ISSUE TITLE
Script no longer works.

### ISSUE THREAD

**Issue by gardotd426** [DrDoctor13/wine-origin-updater#12]
The new versions of Origin no longer have the three options (update for now, always keep origin up to date, etc.) No matter which Lutris script I use to install origin, and even though before I launch I run ./updateorigin.sh, when I launch Origin it opens a window that says it's updating, the progress bar fills as if it is indeed downloading, but when it finishes it just exits out and nothing else happens. I could wait hours and it would never relaunch. If I kill the process and try to launch Origin again, it goes through the exact same process over and over again. The update script gives no errors, it does indeed download and run the script, but it does not work. What doesn't make any sense is that I have about 4 different other versions of Origin for specific games that I downloaded before this issue came up, and those still work. It's not like those are also trying to update or anything. It makes no sense. There is nothing useful in the logs except maybe this:
`Waiting on children
2019-12-02 20:09:14,893: Unable to read stat for process 254431
2019-12-02 20:09:14,893: Unable to read stat for process 254431
Waiting on children`

**Comment by DrDoctor13** [comment]
Do you know what versions of Origin you have? Which ones work? Which one doesn't?

**Comment by gardotd426** [comment]
I can't tell you which ones work because you can't get into the app to check the version. As soon as I launch origin, the update screen immediately pops up. And like I said, it no longer shows the three options, it just starts with the progress bar and says updating. 

The updating window doesn't have a menu bar like the actual client, where you can click Help:About.

The one for battlefield V I just got a couple days ago just now did it too. I'm running the script to see if it works, but it hasn't worked once in the last 3 weeks or so. It's like Origin randomly decides when to do it. I haven't updated my Titanfall 2 launcher in a month, and it hasn't pulled the update thing. 

But also, after this all started happening I went to a couple to preemptively update them, and the update script seems to have actually broken them, unless the timing was just a coincidence. 

Okay. So, it worked for Battlefield V. It's on version 10.5.56.33908 - 0
It quit working for Star Wars Battlefront 2, and my other installation of Battlefield V (something to do with wine and lutris borked the actual game, but the client still did the update thing and updateorigin.sh didn't work). The standalone Origin client did it too, as did my first attempt at Star Wars Jedi: Fallen Order. Luckily I had only just begun downloading it the night before. Like I said, it seems completely random, and before 2 weeks ago, the script worked 100 percent of the time for me. So it seems like it's something goofy with origin.

If you remove the game from lutris and rerun the lutris install script, then Origin works again. But that means losing games that can be 80+GB, which takes FOREVER to replace. Like I've had to replace 2 games and on my 10Mbps connection, it's taking me a week. And people keep saying in forums and stuff that all you have to do is copy the old game files into your new origin prefix. That doesn't work, I've tried it a hundred times. It works with Steam, but for some reason Origin will not see your games. But that's not your purview I know, I'm just saying that's why this is such an issue.

**Comment by DrDoctor13** [comment]
As I've understood it, Origin frequently has issues with its own updates. It is possible they may have changed something in their delivery of updates that breaks my script or they have done something that Wine/Lutris don't like.

See this solution to #9 and see if that helps you at all: https://github.com/DrDoctor13/wine-origin-updater/issues/9#issuecomment-531554358

**Comment by gardotd426** [comment]
@DrDoctor13 That's not a possibility, as there's no "update just for now" option. The first window that pops up is the updating window, as in the update has already started, and there was never any option to do otherwise. This issue has returned. Battlefield V's Origin no longer works whatsoever. I've run the script literally 5 times, and did a fresh install through Lutris using the install script at https://lutris.com/games/battlefield-v 
After running the installation, Origin won't launch, and when it does it throws the "Origin is updating" window. I exit, run the script, launch again, and I get the same window. 
You should be able to easily reproduce this, and you don't even need to own the game. 
- Go to lutris.com/games/battlefield-v
- Click the "Install" button.
- Go through the automated installation process in Lutris. 
- After it's done, try and launch Origin. 
- Run the script, try to launch it again. 
I don't know why this isn't working but it's not working at all and I've been trying for 3 days.

**Comment by gardotd426** [comment]
It's no longer working with the generic Origin installer either.
https://lutris.net/games/origin
I just tried installing it, to see if it was specific to the Battlefield V installer/version, and it's not.

**Comment by superuser-miguel** [comment]
I updated today and was writing a piece on how to update Origin for my forum friends. I came here to check for the old instructions but was met with "Script No Longer works". The script worked for me after updating and I played Star Wars Battlefront II and Battlefield 4. for a brief period of time. 

The script does work.

**Comment by gardotd426** [comment]
@superuser-miguel not all games are affected. Origin installed through some installers won't update to certain Origin versions, some have always worked. Also there have been multiple Origin versions since this issue was posted, so your experience has literally nothing to do with what was happening almost 4 months ago.
