### ISSUE TITLE
Make use of WINEPREFIX

### ISSUE THREAD

**Issue by Trollwut** [DrDoctor13/wine-origin-updater#2]
First of all, thanks for your awesome convenient script!

Any thoughts on implementing the WINEPREFIX variable?

Like that I could run it with `WINEPREFIX=~/Games/origin ./updateorigin.sh` and it automatically does its work in that prefix.

Problem would be to know where the Origin installation folder is. Maybe just try to look for some Origin EXE in two folders (`Program Files (x86)` and `Program Files`) and if it's not found, then ask for the folder as it is now?

Otherwise do its magic. This would prevent errors like spaces in folder names and also makes it easier to manage more than one Origin instance

**Comment by DrDoctor13** [comment]
Hello!
I like this idea and had been imagining something similar, but what can be done if the WINEPREFIX variable is not exported? Is it as simple as checking if the variable is empty?

**Comment by Trollwut** [comment]
Unfortunatelly I don't know, I'm no bash geek… yet :>

But would it be necessary to check?

If you just check if an Origin EXE is existent in `$WINEPREFIX/the/path/to/the.exe`, then it would check in the current directory (+path), will find none and that's it.

If no Origin path has been found, just ask for the Origin directory, as it is now in the script

**Comment by DrDoctor13** [comment]
Check out this new commit and see how it works for you. It checks if WINEPREFIX is passed, checks working directory if WINEPREFIX is not passed, then asks the user for the installation path and checks for Origin.exe.

**Comment by Trollwut** [comment]
Seems like it did work for my x64 WINE prefix!

I removed the `rm` lines in the script to have the file structure remaining. As far as I can tell, it hit the right directory and copied over. Origin started up fine. Haven't tested more, but I think it's ok :)

Now you just have to get rid of the redundant code :>

Also, someone should confirm, especially for a 32 bit prefix

**Comment by DrDoctor13** [comment]
I tested it on my 32-bit prefix and it seemed to work fine.
