### ISSUE TITLE
Syntax error? Not sure how to fix, fairly new to Linux.

### ISSUE THREAD

**Issue by GoblinKisser** [DrDoctor13/wine-origin-updater#5]
Trying to use this, I saved the file in my origin installation folder, and I opened a terminal there and ran the script, but this is what I got. Not sure what this means.

[goblin@andoran Origin]$ ./updateorigin.sh
./updateorigin.sh: line 7: syntax error near unexpected token `newline'
./updateorigin.sh: line 7: `<!DOCTYPE html>'

**Comment by DrDoctor13** [comment]
Try the newest commit and see if that works for you.

**Comment by GoblinKisser** [comment]
That worked perfectly. Thank you!
